spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 776822201363-nbvp3barp58cbgvc7ingfog6a060i8hi.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          github:
            clientId: 134abb4d0740c100ac80
            clientSecret: a3ac81fc82a5f8b5c5f3af5f3326cecb820b6cee
          kakao:
            authorization-grant-type: authorization_code
            client-id: 15d0112b6b872631278206809de2638e
            client-secret: ocUjL3Nr3Zwz5hoe8k0VKLekeTWRqXW0
            scope: profile_nickname
            client-authentication-method: POST
            redirect-uri: http://localhost:8080/login/oauth2/code/{registrationId}
            client-name: Kakao
#          naver:
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8080/login/oauth2/code/naver
#            client-secret: ''
#            scope: name, email
#            client-id: ''
#            client-name: Naver
        provider:
          kakao:
            token-uri: https://kauth.kakao.com/oauth/token
            user-name-attribute: id
            user-info-uri: https://kapi.kakao.com/v2/user/me
            authorization-uri: https://kauth.kakao.com/oauth/authorize
#          naver:
#            user-name-attribute: response
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            token-uri: https://nid.naver.com/oauth2.0/token
